### ISSUE TITLE
知乎登录页面作业反馈

### ISSUE THREAD

**Issue by twhy** [xuqiaoying/xuqiaoying.github.io#1]
作业质量相当不错，看得出很用心，提点改进建议。
1. 可以通过 `input::-webkit-input-placeholder { color: #ccc }` 给 placeholder 设置字体颜色，可能你忘了。
2. 那个 footer 可以用
```css
@media (max-width: 740px) {
  .footer { display: none; }
}
```
隐藏掉，代码的意思是当屏幕宽度 <= 740px，是把 .footer 隐藏掉。
